version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
    pull-request-branch-name:
      separator: "-"
    ignore:
      # ignore patch versions to reduce noise
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      nuget-updates:
        patterns:
          - "*"
