version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
    pull-request-branch-name:
      separator: "-"
    # Disable version updates for NuGet -- currently they create too much noise. Security Updates are on as they use a seperate internal limit
    open-pull-requests-limit: 0
